/**
 * Individual field error detail for validation failures.
 */
export type ValidationErrorDetail = {
  field: string;
  code: string;
  message: string;
  value?: unknown;
  params?: Record<string, unknown>;
};

/**
 * RFC 7807 "Problem Details for HTTP APIs" compatible interface.
 * Standardizes error responses across the entire application.
 * @see https://datatracker.ietf.org/doc/html/rfc7807
 */
export type ProblemDocument = {
  /** A URI reference [RFC3986] that identifies the problem type. */
  type: string;
  /** A short, human-readable summary of the problem type. */
  title: string;
  /** The HTTP status code generated by the origin server for this occurrence of the problem. */
  status: number;
  /** A human-readable explanation specific to this occurrence of the problem. */
  detail: string;
  /** A URI reference that identifies the specific occurrence of the problem. */
  instance?: string;
  /** A stable, application-specific error code (e.g., VALIDATION_ERROR). */
  code: string;
  /** A unique request ID for tracing and debugging. */
  traceId?: string;
  /** Optional array of specific field errors (commonly used for 422 Unprocessable Entity). */
  errors?: ValidationErrorDetail[];
  /** Optional metadata for additional context. */
  meta?: Record<string, unknown>;
  /** Stack trace (only shown in development environments). */
  stack?: string;
};
